POST http://localhost:8080/student/add
Content-Type: application/json

{
  "firstName": "Warunkumarek",
  "lastName": "Chujokodzancy"
}


###
POST http://localhost:8080/students/add
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="input.csv"
Content-Type: text/csv

< ./input.csv
--boundary

